server {
 listen 80;
 server_name _;
 root /usr/share/nginx/html;
 client_max_body_size 513m;
 location /api/ {
  resolver 127.0.0.11 valid=10s ipv6=off;
  set $api http://backend:8080;
  proxy_pass $api;
  proxy_read_timeout 120s;
  proxy_request_buffering off;
  proxy_http_version 1.1;
 }
 location / { try_files $uri $uri/ /index.html; }
}
