CREATE TABLE dataset (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name TEXT NOT NULL, version TEXT NOT NULL,
 storage_key TEXT NOT NULL, root_relative_path TEXT NOT NULL, source_checksum TEXT NOT NULL,
 UNIQUE(name, version)
);

CREATE TABLE capture_log (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 dataset_id BIGINT NOT NULL REFERENCES dataset(id),
 token VARCHAR(64) NOT NULL,
 logfile TEXT NOT NULL,
 location TEXT NOT NULL,
 date_captured TEXT NOT NULL,
 vehicle TEXT NOT NULL,
 raw_payload JSONB NOT NULL,
 UNIQUE(dataset_id, token)
);

CREATE TABLE map_asset (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 dataset_id BIGINT NOT NULL REFERENCES dataset(id),
 token VARCHAR(64) NOT NULL,
 relative_path TEXT NOT NULL,
 category TEXT NOT NULL,
 raw_payload JSONB NOT NULL,
 UNIQUE(dataset_id, token)
);

CREATE TABLE scene (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 dataset_id BIGINT NOT NULL REFERENCES dataset(id),
 token VARCHAR(64) NOT NULL,
 log_token TEXT NOT NULL,
 name TEXT NOT NULL,
 description TEXT NOT NULL,
 nbr_samples INTEGER NOT NULL,
 first_sample_token TEXT NOT NULL,
 last_sample_token TEXT NOT NULL,
 raw_payload JSONB NOT NULL,
 UNIQUE(dataset_id, token)
);

CREATE TABLE sample (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 dataset_id BIGINT NOT NULL REFERENCES dataset(id),
 token VARCHAR(64) NOT NULL,
 scene_token TEXT NOT NULL,
 timestamp_us BIGINT NOT NULL,
 prev_token TEXT,
 next_token TEXT,
 raw_payload JSONB NOT NULL,
 UNIQUE(dataset_id, token)
);

CREATE TABLE sensor (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 dataset_id BIGINT NOT NULL REFERENCES dataset(id),
 token VARCHAR(64) NOT NULL,
 channel TEXT NOT NULL,
 modality TEXT NOT NULL,
 raw_payload JSONB NOT NULL,
 UNIQUE(dataset_id, token)
);

CREATE TABLE calibrated_sensor (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 dataset_id BIGINT NOT NULL REFERENCES dataset(id),
 token VARCHAR(64) NOT NULL,
 sensor_token TEXT NOT NULL,
 translation_x DOUBLE PRECISION NOT NULL,
 translation_y DOUBLE PRECISION NOT NULL,
 translation_z DOUBLE PRECISION NOT NULL,
 rotation_w DOUBLE PRECISION NOT NULL,
 rotation_x DOUBLE PRECISION NOT NULL,
 rotation_y DOUBLE PRECISION NOT NULL,
 rotation_z DOUBLE PRECISION NOT NULL,
 intrinsic00 DOUBLE PRECISION,
 intrinsic01 DOUBLE PRECISION,
 intrinsic02 DOUBLE PRECISION,
 intrinsic10 DOUBLE PRECISION,
 intrinsic11 DOUBLE PRECISION,
 intrinsic12 DOUBLE PRECISION,
 intrinsic20 DOUBLE PRECISION,
 intrinsic21 DOUBLE PRECISION,
 intrinsic22 DOUBLE PRECISION,
 raw_payload JSONB NOT NULL,
 UNIQUE(dataset_id, token)
);

CREATE TABLE ego_pose (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 dataset_id BIGINT NOT NULL REFERENCES dataset(id),
 token VARCHAR(64) NOT NULL,
 timestamp_us BIGINT NOT NULL,
 translation_x DOUBLE PRECISION NOT NULL,
 translation_y DOUBLE PRECISION NOT NULL,
 translation_z DOUBLE PRECISION NOT NULL,
 rotation_w DOUBLE PRECISION NOT NULL,
 rotation_x DOUBLE PRECISION NOT NULL,
 rotation_y DOUBLE PRECISION NOT NULL,
 rotation_z DOUBLE PRECISION NOT NULL,
 raw_payload JSONB NOT NULL,
 UNIQUE(dataset_id, token)
);

CREATE TABLE sample_data (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 dataset_id BIGINT NOT NULL REFERENCES dataset(id),
 token VARCHAR(64) NOT NULL,
 sample_token TEXT NOT NULL,
 ego_pose_token TEXT NOT NULL,
 calibrated_sensor_token TEXT NOT NULL,
 relative_path TEXT NOT NULL,
 fileformat TEXT NOT NULL,
 timestamp_us BIGINT NOT NULL,
 is_key_frame BOOLEAN NOT NULL,
 width INTEGER NOT NULL,
 height INTEGER NOT NULL,
 prev_token TEXT,
 next_token TEXT,
 raw_payload JSONB NOT NULL,
 UNIQUE(dataset_id, token)
);

CREATE TABLE category (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 dataset_id BIGINT NOT NULL REFERENCES dataset(id),
 token VARCHAR(64) NOT NULL,
 name TEXT NOT NULL,
 description TEXT NOT NULL,
 raw_payload JSONB NOT NULL,
 UNIQUE(dataset_id, token)
);

CREATE TABLE object_instance (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 dataset_id BIGINT NOT NULL REFERENCES dataset(id),
 token VARCHAR(64) NOT NULL,
 category_token TEXT NOT NULL,
 nbr_annotations INTEGER NOT NULL,
 first_annotation_token TEXT NOT NULL,
 last_annotation_token TEXT NOT NULL,
 raw_payload JSONB NOT NULL,
 UNIQUE(dataset_id, token)
);

CREATE TABLE visibility (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 dataset_id BIGINT NOT NULL REFERENCES dataset(id),
 token VARCHAR(64) NOT NULL,
 level TEXT NOT NULL,
 description TEXT NOT NULL,
 raw_payload JSONB NOT NULL,
 UNIQUE(dataset_id, token)
);

CREATE TABLE attribute (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 dataset_id BIGINT NOT NULL REFERENCES dataset(id),
 token VARCHAR(64) NOT NULL,
 name TEXT NOT NULL,
 description TEXT NOT NULL,
 raw_payload JSONB NOT NULL,
 UNIQUE(dataset_id, token)
);

CREATE TABLE gt_annotation (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 dataset_id BIGINT NOT NULL REFERENCES dataset(id),
 token VARCHAR(64) NOT NULL,
 sample_token TEXT NOT NULL,
 instance_token TEXT NOT NULL,
 visibility_token TEXT,
 center_x DOUBLE PRECISION NOT NULL,
 center_y DOUBLE PRECISION NOT NULL,
 center_z DOUBLE PRECISION NOT NULL,
 size_w DOUBLE PRECISION NOT NULL,
 size_l DOUBLE PRECISION NOT NULL,
 size_h DOUBLE PRECISION NOT NULL,
 rotation_w DOUBLE PRECISION NOT NULL,
 rotation_x DOUBLE PRECISION NOT NULL,
 rotation_y DOUBLE PRECISION NOT NULL,
 rotation_z DOUBLE PRECISION NOT NULL,
 num_lidar_pts INTEGER NOT NULL,
 num_radar_pts INTEGER NOT NULL,
 prev_token TEXT,
 next_token TEXT,
 raw_payload JSONB NOT NULL,
 UNIQUE(dataset_id, token)
);

ALTER TABLE scene ADD FOREIGN KEY(dataset_id, log_token) REFERENCES capture_log(dataset_id, token);

ALTER TABLE sample ADD FOREIGN KEY(dataset_id, scene_token) REFERENCES scene(dataset_id, token);

ALTER TABLE calibrated_sensor ADD FOREIGN KEY(dataset_id, sensor_token) REFERENCES sensor(dataset_id, token);

ALTER TABLE sample_data ADD FOREIGN KEY(dataset_id, sample_token) REFERENCES sample(dataset_id, token);

ALTER TABLE sample_data ADD FOREIGN KEY(dataset_id, ego_pose_token) REFERENCES ego_pose(dataset_id, token);

ALTER TABLE sample_data ADD FOREIGN KEY(dataset_id, calibrated_sensor_token) REFERENCES calibrated_sensor(dataset_id, token);

ALTER TABLE object_instance ADD FOREIGN KEY(dataset_id, category_token) REFERENCES category(dataset_id, token);

ALTER TABLE gt_annotation ADD FOREIGN KEY(dataset_id, sample_token) REFERENCES sample(dataset_id, token);

ALTER TABLE gt_annotation ADD FOREIGN KEY(dataset_id, instance_token) REFERENCES object_instance(dataset_id, token);

ALTER TABLE gt_annotation ADD FOREIGN KEY(dataset_id, visibility_token) REFERENCES visibility(dataset_id, token);

CREATE TABLE map_log (
 dataset_id BIGINT NOT NULL, map_token VARCHAR(64) NOT NULL, log_token VARCHAR(64) NOT NULL,
 PRIMARY KEY(dataset_id, map_token, log_token),
 FOREIGN KEY(dataset_id, map_token) REFERENCES map_asset(dataset_id, token),
 FOREIGN KEY(dataset_id, log_token) REFERENCES capture_log(dataset_id, token)
);
CREATE TABLE annotation_attribute (
 dataset_id BIGINT NOT NULL, annotation_token VARCHAR(64) NOT NULL, attribute_token VARCHAR(64) NOT NULL,
 PRIMARY KEY(dataset_id, annotation_token, attribute_token),
 FOREIGN KEY(dataset_id, annotation_token) REFERENCES gt_annotation(dataset_id, token),
 FOREIGN KEY(dataset_id, attribute_token) REFERENCES attribute(dataset_id, token)
);
CREATE INDEX idx_scene_dataset ON scene(dataset_id, name);
CREATE INDEX idx_sample_scene_time ON sample(dataset_id, scene_token, timestamp_us);
CREATE INDEX idx_sample_data_frame ON sample_data(dataset_id, sample_token, is_key_frame);
CREATE INDEX idx_gt_sample ON gt_annotation(dataset_id, sample_token);
ALTER TABLE sample_data ADD CHECK (width >= 0 AND height >= 0);
ALTER TABLE gt_annotation ADD CHECK (size_w > 0 AND size_l > 0 AND size_h > 0);
