CREATE EXTENSION IF NOT EXISTS vector;
CREATE TABLE image_embedding (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 dataset_id BIGINT NOT NULL,
 sample_data_token VARCHAR(64) NOT NULL,
 model_name TEXT NOT NULL,
 preprocess TEXT NOT NULL,
 embedding vector(768) NOT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 UNIQUE(dataset_id, sample_data_token, model_name, preprocess),
 FOREIGN KEY(dataset_id, sample_data_token) REFERENCES sample_data(dataset_id, token)
);
