-- Rerun recording of one scene (point cloud + GT, optionally one COMPLETED job's predictions).
-- Lifecycle is separate from auto_label_job: a failed recording is recreated without rerunning VESPA.
CREATE TABLE scene_recording (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 dataset_id BIGINT NOT NULL REFERENCES dataset(id),
 scene_token VARCHAR(64) NOT NULL,
 job_id BIGINT,
 export_version TEXT NOT NULL CHECK (length(trim(export_version))>0),
 sdk_version TEXT NOT NULL CHECK (length(trim(sdk_version))>0),
 status TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','RUNNING','READY','FAILED')),
 execution_token UUID,
 relative_path TEXT,
 size_bytes BIGINT CHECK (size_bytes IS NULL OR size_bytes>0),
 checksum TEXT CHECK (checksum IS NULL OR checksum ~ '^[0-9a-f]{64}$'),
 metadata JSONB CHECK (metadata IS NULL OR jsonb_typeof(metadata)='object'),
 failure_reason TEXT,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 started_at TIMESTAMPTZ,
 completed_at TIMESTAMPTZ,
 FOREIGN KEY(dataset_id,scene_token) REFERENCES scene(dataset_id,token),
 FOREIGN KEY(dataset_id,job_id) REFERENCES auto_label_job(dataset_id,id),
 CHECK (started_at IS NULL OR started_at>=created_at),
 CHECK (completed_at IS NULL OR completed_at>=COALESCE(started_at,created_at)),
 CHECK (
  (status='PENDING' AND started_at IS NULL AND completed_at IS NULL AND failure_reason IS NULL AND execution_token IS NULL
   AND relative_path IS NULL AND size_bytes IS NULL AND checksum IS NULL AND metadata IS NULL)
  OR (status='RUNNING' AND started_at IS NOT NULL AND completed_at IS NULL AND failure_reason IS NULL AND execution_token IS NOT NULL
   AND relative_path IS NULL AND size_bytes IS NULL AND checksum IS NULL AND metadata IS NULL)
  OR (status='READY' AND started_at IS NOT NULL AND completed_at IS NOT NULL AND failure_reason IS NULL AND execution_token IS NOT NULL
   AND relative_path IS NOT NULL AND size_bytes IS NOT NULL AND checksum IS NOT NULL AND metadata IS NOT NULL)
  OR (status='FAILED' AND completed_at IS NOT NULL AND failure_reason IS NOT NULL AND length(trim(failure_reason))>0
   AND relative_path IS NULL AND size_bytes IS NULL AND checksum IS NULL AND metadata IS NULL)
 )
);

-- At most one live (non-FAILED) recording per source/job/export setting; POST reuses it.
CREATE UNIQUE INDEX uq_scene_recording_reuse ON scene_recording(dataset_id,scene_token,(COALESCE(job_id,0)),export_version) WHERE status<>'FAILED';
CREATE INDEX idx_scene_recording_status ON scene_recording(status,created_at);
CREATE INDEX idx_scene_recording_scene ON scene_recording(dataset_id,scene_token,created_at);
CREATE INDEX idx_scene_recording_job ON scene_recording(dataset_id,job_id) WHERE job_id IS NOT NULL;

COMMENT ON COLUMN scene_recording.relative_path IS 'Relative to recording.root (rerun_recordings volume); served only via /api/recordings/{id}/content.';
COMMENT ON COLUMN scene_recording.metadata IS 'Spring-built camelCase view: applicationId, rerunRecordingId, timeline, timeTimeline, entities, samples[index,sampleToken,timestampUs,lidarPoints,gtAnnotationIds,predictionIds].';
COMMENT ON COLUMN scene_recording.execution_token IS 'Worker dispatch UUID; READY/FAILED updates require the same token while RUNNING.';
